#!/bin/bash
# Linux service venv run for multilauncher create multilaunch venv in /usr/share and copy source projects in /usr/share/multilauncher/build
# Emanuele Paiano nixw0rm@gmail.com

CURRENT_PATH=$(dirname "$0")
MULTI_LAUNCHER_PATH=$CURRENT_PATH
VENV_PATH=$MULTI_LAUNCHER_PATH/venv

cat<< "__EOF__"
___  ___      _ _   _ _                        _               
|  \/  |     | | | (_) |                      | |              
| .  . |_   _| | |_ _| | __ _ _   _ _ __   ___| |__   ___ _ __ 
| |\/| | | | | | __| | |/ _` | | | | '_ \ / __| '_ \ / _ \ '__|
| |  | | |_| | | |_| | | (_| | |_| | | | | (__| | | |  __/ |   
\_|  |_/\__,_|_|\__|_|_|\__,_|\__,_|_| |_|\___|_| |_|\___|_|   
                                                             
                version 0.0.1-SNAPSHOT

__EOF__

set -e

(source $VENV_PATH/bin/activate && echo "Virtual Environment enabled." || (echo "$VENV_PATH/activate not found." && exit 1)) && 
($VENV_PATH/bin/python $MULTI_LAUNCHER_PATH/main.py || (echo "Error while running $MULTI_LAUNCHER_PATH/main.py" && exit 1))
